### ISSUE TITLE
Website is dead, would like to add the list into repo entry

### ISSUE THREAD

**Issue by BradKML** [vikasnair/behind_thoughts#1]
Recently someone has proposed alternate Blique Decks https://github.com/dcrgll/vscode-oblique-strategies/issues/2
And I have compiled some of them in https://github.com/BrandonKMLee/vscode-oblique-strategies/commit/46c6cac78671b6af2c8cfe0004be3f4a8aee7e07
IS it possible to share your database for me to archive and add to the code?

**Comment by vikasnair** [comment]
Thanks for the interest. There were only a handful of uploads, and all came from the original deck. This was just a school project, and was never improved on.
